services:
  # 依存関係インストール
  node-install:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    command: npm install

  # Vite開発サーバー
  node-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev"

  # Viteビルド
  node-build:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    command: sh -c "npm install && npm run build"

  # Viteプレビューサーバー
  node-preview:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    ports:
      - "4173:4173"
    command: sh -c "npm install && npm run preview"

  # テスト実行環境
  node-test:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    environment:
      - CI=true
    command: sh -c "npm install && npm run test:run"

  # Playwright E2Eテスト環境
  playwright:
    image: mcr.microsoft.com/playwright:v1.53.0-jammy
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    environment:
      - CI=true
      - HOME=/tmp
    command: sh -c "npm install && npm run test:e2e"
