services:
  # 依存関係インストール
  node-install:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    command: npm install

  # Vite開発サーバー
  node-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev"

  # Viteビルド
  node-build:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    command: sh -c "npm install && npm run build"

  # Viteプレビューサーバー
  node-preview:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./posture-diagnosis:/app
    ports:
      - "4173:4173"
    command: sh -c "npm install && npm run preview"
